### ISSUE TITLE
Update readme daily?

### ISSUE THREAD

**Issue by knmcguire** [WeeklyRobotics/robotic_events#31]
The events haven't been updated in a while, but since that hasn't happened yet, the [readme ](https://github.com/WeeklyRobotics/robotic_events/blob/main/README.md)and the [website ](https://www.weeklyrobotics.com/events) are quite out of date.

Any particular reason why we'd not like to do this daily? Or weekly at least?

**Comment by msadowski** [comment]
This was an issue with the action workflow and my understanding of actions. We had a prune action that cleans up the list of events, and an action to recreate readme on push. It was my expectation that trimming the list would cause the recreate event to fire up but that's not the case. I've modified the action now to work daily 5 minutes past midnight and on push. Thanks for reporting this! Also, your name was not coming up in the readme and I fixed that too. Thanks!!

**Comment by knmcguire** [comment]
Ah that with my name was actually something that it had to be changed in the template, since it was overwritten again. I've fixed it in this commit https://github.com/WeeklyRobotics/robotic_events/commit/b61cec4581f7fca3e7aee6318ef7e6d096b74034
